#!/usr/bin/env node

/**
 * Embeds llms-full.txt content into src/data/docs.ts at build time.
 * The parsing happens at runtime when the server starts.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const docsPath = resolve(__dirname, '../../../llms-full.txt');
const outputPath = resolve(__dirname, '../src/data/docs.ts');

// Ensure the data directory exists
mkdirSync(dirname(outputPath), { recursive: true });

// Read the docs file
const docsContent = readFileSync(docsPath, 'utf-8');

// Escape backticks and backslashes for template literal
// Only escape ${, not plain $
const escaped = docsContent
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

// Generate the TypeScript file
const output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/embed-docs.js during prebuild

/**
 * Raw documentation content from llms-full.txt
 * Parsed into sections at runtime by the parser
 */
export const rawDocs = \`${escaped}\`;
`;

writeFileSync(outputPath, output, 'utf-8');

console.log('Embedded docs into src/data/docs.ts');
