# Example GitHub Actions workflow for running benchmarks
# Copy this to .github/workflows/benchmarks.yml in your repository

name: Performance Benchmarks

on:
  pull_request:
    paths:
      - 'packages/core/**'
      - 'packages/adapter-*/**'
      - 'packages/store-*/**'
      - 'packages/runtime/**'
  push:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build packages
        run: pnpm build
      
      # For PRs, download baseline from main branch
      - name: Download baseline (PR only)
        if: github.event_name == 'pull_request'
        uses: actions/download-artifact@v3
        with:
          name: benchmark-baseline
          path: packages/benchmarks
        continue-on-error: true
      
      - name: Run benchmarks
        run: pnpm bench:ci
      
      - name: Compare with baseline (PR only)
        if: github.event_name == 'pull_request'
        run: |
          if [ -f packages/benchmarks/bench-baseline.json ]; then
            pnpm bench:compare
          else
            echo "No baseline found, skipping comparison"
          fi
      
      # Save results as baseline for main branch
      - name: Upload baseline (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-baseline
          path: packages/benchmarks/bench-results.json
          retention-days: 30
      
      # Always upload results for inspection
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results-${{ github.sha }}
          path: packages/benchmarks/bench-results.json
      
      # Comment on PR with results (optional)
      - name: Comment PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read comparison output if available
            let comment = '## 📊 Performance Benchmark Results\n\n';
            
            try {
              const results = fs.readFileSync(
                path.join(process.env.GITHUB_WORKSPACE, 'packages/benchmarks/bench-results.json'),
                'utf8'
              );
              const data = JSON.parse(results);
              
              // Add summary
              comment += `Ran ${data.numTotalTests || 0} benchmarks\n\n`;
              
              // Add link to full results
              comment += `[View full results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\n`;
            } catch (e) {
              comment += '❌ Failed to read benchmark results\n';
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });